/* Generated by scripts/update-offline.py. Do not edit sw.js directly. */
'use strict';

const CACHE_PREFIX = 'recipes-offline-' + new URL(self.registration.scope).pathname + ':';
const CACHE_NAME = CACHE_PREFIX + 'aef8eae3e12eb2c4';
const RECIPE_COUNT = 50;
const FILES = [
  "index.html",
  "styles.css",
  "pwa.css",
  "pwa.js",
  "reminders.js",
  "manifest.webmanifest",
  "offline.html",
  "shortcuts/recipe-ingredients.shortcut",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "beef/bbq-beef-burger-meal-prep.html",
  "beef/beef-tataki.html",
  "beef/beef-tenderloin-roast.html",
  "beef/big-mac-protein-bowls.html",
  "beef/boeuf-bourguignon-julia-child.html",
  "beef/broccolini-beef-stir-fry-meal-prep.html",
  "beef/chaoshan-pickled-mustard-beef-stir-fry.html",
  "beef/dan-dan-inspired-noodles.html",
  "beef/low-and-slow-eye-of-round.html",
  "beef/marinated-roast-beef.html",
  "beef/mexican-shredded-beef-tacos.html",
  "beef/pepper-beef-pasta-meal-prep.html",
  "beef/rump-cap-roast-picanha.html",
  "beef/sticky-hoisin-beef-bowls.html",
  "chicken/african-chicken-curry-kuku-paka.html",
  "chicken/breakfast-bowls-meal-prep.html",
  "chicken/chicken-cacciatore.html",
  "chicken/chicken-chasseur.html",
  "chicken/chicken-kale-salad.html",
  "chicken/chicken-mushroom-protein-pasta.html",
  "chicken/chicken-potato-bake-meal-prep.html",
  "chicken/chicken-rendang-curry-meal-prep.html",
  "chicken/chicken-shawarma.html",
  "chicken/chicken-vegetable-rice.html",
  "chicken/chipotle-chicken-smoky-rice.html",
  "chicken/mexican-shredded-chicken.html",
  "chicken/one-pot-mexican-chicken-rice.html",
  "chicken/oven-baked-chicken-breast.html",
  "chicken/poached-chicken.html",
  "chicken/slow-cooker-mexican-chicken-soup.html",
  "chicken/sweet-sour-chicken-meal-prep.html",
  "chicken/thai-grilled-chicken-gai-yang.html",
  "lamb/12-hour-roast-lamb.html",
  "lamb/massaman-lamb-shoulder.html",
  "pork/chorizo-egg-muffins.html",
  "pork/filipino-pork-adobo.html",
  "pork/olive-vegetable-minced-pork-green-beans.html",
  "pork/pork-tenderloin-honey-garlic.html",
  "pork/pulled-pork.html",
  "pork/taiwanese-braised-pork-rice.html",
  "seafood/chaoshan-jinbuhuan-clams.html",
  "seafood/chaoshan-shacha-three-delicacies.html",
  "seafood/crispy-pan-fried-white-fish.html",
  "seafood/crispy-skin-fish.html",
  "seafood/jerk-fish.html",
  "seafood/lemon-garlic-salmon-tray-bake.html",
  "seafood/steamed-squid-scallion-oil.html",
  "seafood/xo-shrimp-fried-rice.html",
  "vegetable/mung-bean-sprouts-two-ways.html",
  "vegetable/pea-shoots-three-ways.html"
];
const URLS = FILES.map((file) => new URL(file, self.registration.scope).href);
const KNOWN_URLS = new Set(URLS);

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    // addAll is atomic: a missing page or interrupted download fails installation.
    // A previous complete version stays active until the entire new one is saved.
    await cache.addAll(URLS.map((url) => new Request(url, { cache: 'reload' })));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
      .map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type !== 'OFFLINE_STATUS' || !event.ports[0]) return;
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    const entries = await Promise.all(URLS.map((url) => cache.match(url)));
    event.ports[0].postMessage({
      type: 'OFFLINE_STATUS',
      ready: entries.every(Boolean),
      recipeCount: RECIPE_COUNT
    });
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  const scope = new URL(self.registration.scope);
  if (request.method !== 'GET' || url.origin !== scope.origin || !url.pathname.startsWith(scope.pathname)) return;
  url.search = '';
  url.hash = '';
  if (url.href === scope.href) url.pathname += 'index.html';

  if (!KNOWN_URLS.has(url.href) && request.mode !== 'navigate') return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE_NAME);
    if (KNOWN_URLS.has(url.href)) {
      const saved = await cache.match(url.href);
      if (saved) return saved;
    }
    try {
      return await fetch(request);
    } catch (error) {
      if (request.mode === 'navigate') {
        const saved = await cache.match(new URL('offline.html', scope).href);
        if (saved) {
          // Resolve fallback links from the app root even for an unknown deep URL.
          const html = (await saved.text()).replace('<head>', '<head><base href="' + scope.href + '">');
          return new Response(html, { status: 503, headers: { 'Content-Type': 'text/html; charset=utf-8' } });
        }
      }
      return Response.error();
    }
  })());
});
